name: "godot-ci export"
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "steam-v*"

env:
  GODOT_VERSION: 4.3
  GAME_NAME: bookworm
  PROJECT_PATH: "./src/"

jobs:
  export-windows:
    name: Export game for Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Export
        id: export
        uses: bjornarprytz/godot-export@v5.3.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{env.GODOT_VERSION}}/Godot_v${{env.GODOT_VERSION}}-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{env.GODOT_VERSION}}/Godot_v${{env.GODOT_VERSION}}-stable_export_templates.tpz
          relative_project_path: ${{ env.PROJECT_PATH }}
          use_preset_export_path: true
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.windows
          path: ${{ steps.export.outputs.build_directory }}/Windows Desktop

  deployToSteam:
    name: Deploy to Steam
    needs: [export-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Download Artifact (Windows)
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.windows
          path: bookworm
      - name: Deploy to Steam
        uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
          appId: ${{ secrets.STEAM_APP_ID}}
          buildDescription: ${{ env.RELEASE_VERSION }}
          releaseBranch: release
          depot1Path: bookworm
